package ap.ex2.bookscrabble.common;

public enum Command {
    GO_TO_GAME_SCENE,
    UPDATE_GAME_BOARD,
    UPDATE_GAME_TILES,
    PLAY_START_GAME_SOUND,
    INVALID_WORD_PLACEMENT,
    UPDATE_SCORE_BOARD, RESET_SELECTIONS,  DISPLAY_PORT,

    SOUND_NEW_PLAYER_JOINED,
    DISPLAY_CHALLENGE_PROMPT, SOUND_NEW_WORD

}
